function stProcess = vocoder_init(M,window,noverlap,fs)
    % theese two fields always have to be fields of stProcess because they 
    % will be used from the ola_framework:
    stProcess = struct(...
        'thisInputBlock',[],...
        'thisOutputBlock',[],...
        'nOverlap',noverlap,...
        'nShift',length(window)-noverlap,...
        'blockLen',length(window),...
        'blockNumber',[],...
        'M',M,...
        'f0vec',[0,0,0],...
        'fs',fs,...
        'w',window,...
        'f0_tracker',zeros(100,1),...
        'dkPulsetrain',1,...
        'mPhiPulsetrain',1,...
        'fltStates', rand(M,1),...
        'idx',[],...
        's',[]);
end